# Generated by Django 5.2 on 2025-06-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquriy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('labour law', 'LABOUR LAW'), ('tax law', 'TAX LAW'), ('other', 'OTHER')], default='TAX LAW', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='AdovacteProfile',
            new_name='AdvocateProfile',
        ),
    ]
