# Generated by Django 5.2 on 2025-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0004_enquriy_description_enquriy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('labour law', 'LABOUR LAW'), ('tax law', 'TAX LAW'), ('other', 'OTHER')], default='TAX LAW', max_length=100)),
                ('description', models.TextField()),
                ('case_document', models.ImageField(blank=True, null=True, upload_to='caseimg/')),
                ('total_no_hearings', models.IntegerField()),
                ('court_name', models.CharField(max_length=100)),
                ('fee', models.IntegerField(default=500)),
            ],
        ),
    ]
