# Generated by Django 5.2 on 2025-06-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelname',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelname',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelname',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelname',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
        migrations.AddField(
            model_name='modelname',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelname',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
