# Generated by Django 5.2 on 2025-06-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btrapp', '0002_modelname_address_modelname_city_modelname_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
    ]
