# Generated by Django 5.2 on 2025-06-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btrapp', '0004_enquriy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquriy',
        ),
    ]
