# Generated by Django 5.2 on 2025-06-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btrapp', '0005_delete_enquriy'),
        ('lawfirmapp', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='lawfirmapp.appointment')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdvocateProfiles', to='lawfirmapp.advocateprofile')),
            ],
        ),
    ]
